title: Kickin' the GH Pages' tires
author: twalker
email: tim.twalker@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nothing to see here. Just trying out GitHub's Pages hosting.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
